# Generated by Django 5.2.1 on 2025-06-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], unique=True)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('istirahat_mulai', models.TimeField(help_text='Waktu mulai istirahat')),
                ('istirahat_selesai', models.TimeField(help_text='Waktu selesai istirahat')),
            ],
            options={
                'verbose_name': 'Jadwal Harian',
                'verbose_name_plural': 'Pengaturan Jadwal Harian',
                'ordering': ['hari'],
            },
        ),
        migrations.CreateModel(
            name='JadwalGenetika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.JSONField()),
                ('hasil_jadwal', models.JSONField()),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10)),
                ('tanggal_publikasi', models.DateField(blank=True, null=True)),
                ('tahun_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_genetika_set', to='data.tahunakademik')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('dosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.dosen')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.kelas')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.matakuliah')),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ruangan')),
                ('tahun_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_set', to='data.tahunakademik')),
            ],
            options={
                'verbose_name': 'Jadwal Kuliah (Hasil)',
                'verbose_name_plural': 'Jadwal Kuliah (Hasil)',
                'ordering': ['tahun_akademik', 'hari', 'jam_mulai', 'kelas'],
                'unique_together': {('tahun_akademik', 'hari', 'jam_mulai', 'dosen'), ('tahun_akademik', 'hari', 'jam_mulai', 'kelas'), ('tahun_akademik', 'hari', 'jam_mulai', 'ruangan')},
            },
        ),
    ]
