# Generated by Django 5.2.1 on 2025-06-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sijaku', '0017_alter_jadwal_unique_together_remove_jadwal_dosen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], unique=True)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('istirahat_mulai', models.TimeField(help_text='Waktu mulai istirahat')),
                ('istirahat_selesai', models.TimeField(help_text='Waktu selesai istirahat')),
            ],
            options={
                'verbose_name': 'Jadwal Harian',
                'verbose_name_plural': 'Pengaturan Jadwal Harian',
                'ordering': ['hari'],
            },
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.PositiveSmallIntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('dosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sijaku.dosen')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.kelas')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.matakuliah')),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sijaku.ruangan')),
                ('tahun_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_set', to='sijaku.tahunakademik')),
            ],
            options={
                'verbose_name': 'Jadwal Kuliah (Hasil)',
                'verbose_name_plural': 'Jadwal Kuliah (Hasil)',
                'ordering': ['tahun_akademik', 'hari', 'jam_mulai', 'kelas'],
                'unique_together': {('tahun_akademik', 'hari', 'jam_mulai', 'dosen'), ('tahun_akademik', 'hari', 'jam_mulai', 'kelas'), ('tahun_akademik', 'hari', 'jam_mulai', 'ruangan')},
            },
        ),
    ]
