services:
  redis:
    image: redis:8-alpine
    ports:
      - "6379:6379"

  db:
    image: mariadb:11.7.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: sijaku
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmydadmin:
    image: phpmyadmin:5.2.2-apache
    ports:
      - "8080:80"

volumes:
  db_data: