# Generated by Django 5.2.1 on 2025-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_alter_jabatan_dosen"),
    ]

    operations = [
        migrations.CreateModel(
            name="MataKuliah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10, unique=True)),
                ("nama", models.CharField(max_length=100)),
                ("sks", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Mata Kuliah",
                "verbose_name_plural": "Mata Kuliah",
                "ordering": ["kode"],
            },
        ),
    ]
