# Generated by Django 5.2.1 on 2025-06-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0007_ruangan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PemetaanDosenMK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosen_pengampu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pengampu_matakuliah",
                        to="sijaku.dosen",
                    ),
                ),
                (
                    "matakuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penyelenggaraan",
                        to="sijaku.matakuliah",
                    ),
                ),
                (
                    "tahun_akademik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penyelenggaraan",
                        to="sijaku.tahunakademik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pemetaan Dosen-MK",
                "verbose_name_plural": "Pemetaan Dosen-MK",
                "ordering": ["tahun_akademik", "matakuliah"],
                "unique_together": {("tahun_akademik", "matakuliah")},
            },
        ),
    ]
