# Generated by Django 5.2.1 on 2025-06-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0009_alter_jabatan_dosen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Peminatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=10, unique=True)),
                ("nama", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Peminatan",
                "verbose_name_plural": "Peminatan",
                "ordering": ["kode"],
            },
        ),
        migrations.AddField(
            model_name="matakuliah",
            name="tipe",
            field=models.CharField(
                choices=[("teori", "Teori"), ("praktik", "Praktik")],
                default="teori",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="matakuliah",
            name="peminatan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matakuliah",
                to="data.peminatan",
            ),
        ),
    ]
