# Generated by Django 5.2.1 on 2025-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0010_peminatan_matakuliah_tipe_matakuliah_peminatan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruangan",
            name="keterangan",
        ),
        migrations.AddField(
            model_name="ruangan",
            name="kapasitas",
            field=models.PositiveIntegerField(
                default=1, help_text="Jumlah kelas yang dapat ditampung"
            ),
            preserve_default=False,
        ),
    ]
