# Generated by Django 5.2.1 on 2025-06-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0011_remove_ruangan_keterangan_ruangan_kapasitas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kelas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tahun_angkatan",
                    models.PositiveIntegerField(
                        help_text="Tahun angkatan mahasiswa, misal 2023 untuk mahasiswa angkatan 2023"
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        help_text="Contoh: A, B, C", max_length=20, unique=True
                    ),
                ),
                (
                    "peminatan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kosongkan jika ini adalah kelas umum (bukan peminatan).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kelas",
                        to="sijaku.peminatan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kelas",
                "verbose_name_plural": "Kelas",
                "ordering": ["tahun_angkatan", "nama"],
                "unique_together": {("tahun_angkatan", "nama")},
            },
        ),
    ]
