# Generated by Django 5.2.1 on 2025-06-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0012_kelas"),
    ]

    operations = [
        migrations.CreateModel(
            name="JadwalHarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hari",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Senin"),
                            (1, "Selasa"),
                            (2, "Rabu"),
                            (3, "Kamis"),
                            (4, "Jumat"),
                            (5, "Sabtu"),
                            (6, "Minggu"),
                        ],
                        unique=True,
                    ),
                ),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                (
                    "istirahat_mulai",
                    models.TimeField(help_text="Waktu mulai istirahat"),
                ),
                (
                    "istirahat_selesai",
                    models.TimeField(help_text="Waktu selesai istirahat"),
                ),
            ],
            options={
                "verbose_name": "Jadwal Harian",
                "verbose_name_plural": "Pengaturan Jadwal Harian",
                "ordering": ["hari"],
            },
        ),
    ]
