# Generated by Django 5.2.1 on 2025-06-20 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0015_alter_kelas_unique_together_alter_kelas_nama_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidasiPemetaanDosenMK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("diajukan", "Diajukan ke WD1"),
                            ("disetujui", "Disetujui WD1"),
                            ("ditolak", "Ditolak WD1"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("diajukan_pada", models.DateTimeField(blank=True, null=True)),
                ("divalidasi_pada", models.DateTimeField(blank=True, null=True)),
                ("catatan", models.TextField(blank=True)),
                (
                    "diajukan_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pengajuan_pemetaan",
                        to="data.dosen",
                    ),
                ),
                (
                    "divalidasi_oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validasi_pemetaan_wd1",
                        to="data.dosen",
                    ),
                ),
                (
                    "tahun_akademik",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validasi_pemetaan",
                        to="data.tahunakademik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validasi Pemetaan Dosen-MK",
                "verbose_name_plural": "Validasi Pemetaan Dosen-MK",
            },
        ),
        migrations.CreateModel(
            name="ValidasiPemetaanDosenMKLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aksi",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("diajukan", "Diajukan ke WD1"),
                            ("disetujui", "Disetujui WD1"),
                            ("ditolak", "Ditolak WD1"),
                        ],
                        max_length=50,
                    ),
                ),
                ("waktu", models.DateTimeField(default=django.utils.timezone.now)),
                ("catatan", models.TextField(blank=True)),
                (
                    "oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data.dosen",
                    ),
                ),
                (
                    "validasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histori",
                        to="data.validasipemetaandosenmk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histori Validasi Pemetaan Dosen-MK",
                "verbose_name_plural": "Histori Validasi Pemetaan Dosen-MK",
                "ordering": ["-waktu"],
            },
        ),
    ]
