# Generated by Django 5.1.4 on 2025-05-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dosen', 'Dosen'), ('staf', 'Staf'), ('admin', 'Admin')], max_length=10),
        ),
    ]
