# Generated by Django 5.2.1 on 2025-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dosen',
                'verbose_name_plural': 'Dosen',
                'ordering': ['nama'],
            },
        ),
    ]
