# Generated by Django 5.2.1 on 2025-05-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jabatan', to='sijaku.dosen'),
        ),
    ]
