# Generated by Django 5.2.1 on 2025-05-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0002_staf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staf',
        ),
    ]
