# Generated by Django 5.1.4 on 2025-05-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0002_alter_dosen_user_alter_staf_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JamKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai', models.TimeField()),
                ('selesai', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('sks', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('tipe', models.CharField(choices=[('teori', 'Teori'), ('praktik', 'Praktik')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('kapasitas', models.PositiveIntegerField()),
                ('tipe', models.CharField(choices=[('kelas', 'Kelas'), ('lab', 'Lab Komputer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPerkuliahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=5)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.dosen')),
                ('hari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.hari')),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.jamkuliah')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.matakuliah')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sijaku.ruangan')),
            ],
            options={
                'unique_together': {('hari', 'jam', 'ruangan')},
            },
        ),
    ]
