# Generated by Django 5.1.4 on 2025-05-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0003_hari_jamkuliah_matakuliah_ruangan_jadwalperkuliahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='dosen_pengampu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mata_kuliah_diampu', to='sijaku.dosen'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='usulan_dosen',
            field=models.ManyToManyField(blank=True, related_name='mata_kuliah_diusulkan', to='sijaku.dosen'),
        ),
    ]
