# Generated by Django 5.2.1 on 2025-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0004_matakuliah_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
