# Generated by Django 5.2.1 on 2025-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sijaku", "0005_alter_matakuliah_semester"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="matakuliah",
            options={
                "ordering": ["semester", "kode"],
                "verbose_name": "Mata Kuliah",
                "verbose_name_plural": "Mata Kuliah",
            },
        ),
        migrations.CreateModel(
            name="TahunAkademik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.CharField(max_length=9)),
                (
                    "semester",
                    models.CharField(
                        choices=[("ganjil", "Ganjil"), ("genap", "Genap")],
                        default="ganjil",
                        max_length=10,
                    ),
                ),
                ("aktif", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Tahun Akademik",
                "verbose_name_plural": "Tahun Akademik",
                "ordering": ["-tahun"],
                "unique_together": {("tahun", "semester")},
            },
        ),
    ]
