# Generated by Django 5.2.1 on 2025-06-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0008_pemetaandosenmk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatan',
            name='dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jabatan', to='sijaku.dosen'),
        ),
    ]
