# Generated by Django 5.2.1 on 2025-06-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0015_alter_kelas_unique_together_alter_kelas_nama_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'ordering': ['tahun_akademik', 'hari', 'jam_mulai'], 'verbose_name': 'Jadwal Kuliah (Hasil)', 'verbose_name_plural': 'Jadwal Kuliah (Hasil)'},
        ),
        migrations.AlterUniqueTogether(
            name='jadwal',
            unique_together={('tahun_akademik', 'hari', 'jam_mulai', 'dosen'), ('tahun_akademik', 'hari', 'jam_mulai', 'ruangan')},
        ),
        migrations.AddField(
            model_name='jadwal',
            name='list_kelas',
            field=models.ManyToManyField(related_name='jadwal_set', to='sijaku.kelas'),
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='kelas',
        ),
    ]
