# Generated by Django 5.2.1 on 2025-06-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sijaku', '0016_validasipemetaandosenmk_validasipemetaandosenmklog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jadwal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='dosen',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='matakuliah',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='ruangan',
        ),
        migrations.RemoveField(
            model_name='jadwal',
            name='tahun_akademik',
        ),
        migrations.DeleteModel(
            name='JadwalHarian',
        ),
        migrations.DeleteModel(
            name='Jadwal',
        ),
    ]
